{
 "title": "Slurm Monitoring Dashboard",
 "description": "Dashboard to monitor various attributes of Slurm Cluster",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Partitions gpu-2080ti Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"usage_details\")\n  |> filter(fn: (r) => r[\"_field\"] == \"t_gpu\")\n  |> filter(fn: (r) => r[\"partition\"] == \"gpu-2080ti\" or r[\"partition\"] == \"gpu-2080ti-dev\" or r[\"partition\"] == \"gpu-2080ti-interactive\" or r[\"partition\"] == \"gpu-2080ti-long\" or r[\"partition\"] == \"gpu-2080ti-preemptable\")\n  |> group(columns:[\"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> group(columns: [\"_value\", \"_time\"], mode: \"except\")  \n  |> yield()"
    }
   ]
  },
  {
   "title": "Partitions gpu-v100 Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"usage_details\")\n  |> filter(fn: (r) => r[\"_field\"] == \"t_gpu\")\n  |> filter(fn: (r) => r[\"partition\"] == \"gpu-v100\")\n  |> group(columns:[\"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> group(columns: [\"_value\", \"_time\"], mode: \"except\")  \n  |> yield()\n"
    }
   ]
  },
  {
   "title": "Partitions CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"usage_details\")\n  |> filter(fn: (r) => r[\"_field\"] == \"t_cpu\")\n  |> filter(fn: (r) => r[\"partition\"] == \"cpu-long\" or r[\"partition\"] == \"cpu-preemptable\")\n  |> group(columns:[\"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> group(columns: [\"_value\", \"_time\"], mode: \"except\")\n  |> yield()\n\n\n"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "/mnt/qb/work/bethge Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "  from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qinfo_quota\")\n  |> filter(fn: (r) => r[\"measure\"] == \"bethge\" or r[\"measure\"] == \"49ebf8c4-c625-4e05-82bf-baac59cba9dd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "/mnt/qb/bethge Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qinfo_quota\")\n  |> filter(fn: (r) => r[\"measure\"] == \"8ebdf33e-4dfe-4f07-aaf9-06ae3b1acbc0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Disk write times at /mnt/qb/work/bethge",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qb_write_time\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_taken\")\n  |> filter(fn: (r) => r[\"location\"] == \"/mnt/qb/bethge\" or r[\"location\"] == \"/mnt/qb/home/bethge\" or r[\"location\"] == \"/mnt/qb/work/bethge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Job Pending Reasons", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Last time Jobs Waiting in Queue for Partition",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jobs_waiting\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Jobs Waiting - Reasons",
   "type": "timeseries",
   "description": "This plot shows why the jobs are in a pending state for a given partition.",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jobs_waiting_reasons\")\n  |> group(columns: [\"partition\", \"reason\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Total Usage on the cluster and sdiag information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Jobs Status Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sdiag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"jobs.canceled\" or r[\"_field\"] == \"jobs.failed\" or r[\"_field\"] == \"jobs.completed\" or r[\"_field\"] == \"jobs.started\" or r[\"_field\"] == \"jobs.submitted\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "Non Responding Nodes",
   "type": "table",
   "description": "These are nodes that are down. This is issued from slurm and in the future would also include faulty nodes.",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: -40s)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_state\")\n  |> filter(fn: (r) => r[\"_field\"] == \"responding\")\n  |> filter(fn: (r) => r[\"state\"] == \"down\" or r[\"state\"] == \"drained\")\n  |> filter(fn: (r) => r[\"_value\"] == 0)\n  |> group(columns: [\"_time\"])\n  |> keep(columns: [\"hostname\", \"state\"])\n"
    }
   ]
  },
  {
   "title": "Slurm Backfill jobs Since a reset",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sdiag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bf_jobs_since_reset\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "Slurm Backfill jobs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sdiag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bf_jobs\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "sdiag last thread count (Server Thread Count)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 15, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sdiag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"thread_count\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "Slurm Backfill Cycles",
   "type": "timeseries",
   "description": "A backfilling scheduling cycle implies to get locks for jobs, nodes and partitions objects then trying to get resources for jobs pending",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sdiag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"last_cycle_usec\" or r[\"_field\"] == \"mean_cycle_usec\")\n  |> filter(fn: (r) => r[\"section\"] == \"scheduler_backfill\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "Slurm Cycles",
   "type": "timeseries",
   "description": "Last Scheduling Cycle - Time in microseconds for last job schedule.\nMean Scheduling Cycle - Mean Time in microseconds for all job schedules.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sdiag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"last_cycle_usec\" or r[\"_field\"] == \"mean_cycle_usec\")\n  |> filter(fn: (r) => r[\"section\"] == \"scheduler_main\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "Non-Responsive Nodes",
   "type": "timeseries",
   "description": "This show the nodes that are not responding at the current moment from slurm",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"tueslurm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_state\")\n  |> filter(fn: (r) => r[\"_field\"] == \"responding\")\n  |> filter(fn: (r) => r[\"state\"] == \"down\" or r[\"state\"] == \"drained\")\n  |> filter(fn: (r) => r[\"_value\"] == 0)\n  |> group(columns:[\"_time\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false)\n  |> group(columns: [\"_value\", \"_time\"], mode: \"except\")  \n  |> yield()"
    }
   ]
  }
 ]
}